config/routes.rb
Rails.application.routes.draw do
  root to: "homepages#index"

  get '/:slug', to: 'links#short', as: :short

  resources :links, only: [:show, :destroy, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  has_many :link_clicks, dependent: :destroy

  def short
    Rails.application.routes.url_helpers.short_url(slug: slug)
  end
end

app/models/link_click.rb
class LinkClick < ApplicationRecord
  has_one :link
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  private

  # Use this as a before filter to prevent caching for certain actions
  def prevent_browser_caching
    response.headers['Cache-Control'] = 'no-cache, no-store, must-revalidate'
    response.headers['Pragma'] = 'no-cache'
    response.headers['Expires'] = '0'
  end
end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
  before_action :link_form, only: [:index]
  before_action :prevent_browser_caching, only: [:index]

  def index
    @links = Link.order(created_at: :desc)
  end

  def link_form
    @link_form ||= LinkForm.new
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link_by_slug, only: [:short]
  before_action :set_link_by_id, only: [:show, :destroy]

  before_action :link_form, only: [:create]

  def short
    return render 'errors/404', status: :not_found if @link.nil?

    @link.link_clicks.create!
    redirect_to @link.url
  end

  def show
    @graph_link_presenter = ::GraphLinkPresenter.new(link: @link, end_time: params[:end_time])
  end

  def destroy
    if @link.destroy
      render json: {
        success: true,
        link_id: params[:id],
        message: "Shorten link with slug #{@link.slug} deleted !"
      }, status: :ok
    else
      render json: {
        success: false,
        link_id: params[:id],
        message: "Unable to delete shorten link with slug #{@link.slug}"
      }
    end
  end

  def create
    if @link_form.submit
      render json: {
        success: true,
        partial: render_to_string(
          'homepages/_link_row',
          layout: false,
          locals: { link: @link_form.link }
        ),
        message: "Shorten link with slug #{@link_form.link.slug} created !" 
      }, status: :created
    else
      render json: {
        success: false,
        partial: render_to_string('shared/_list_errors', layout: false, locals: { errors: @link_form.errors[:url] })
      }
    end
  end

  private

  def set_link_by_slug
    @link ||= Link.find_by(slug: params[:slug])
  end

  def set_link_by_id
    @link ||= Link.find(params[:id])
  end

  def link_form
    @link_form ||= LinkForm.new(link_params)
  end

  def link_params
    params[:link_form].permit(:url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepages_helper.rb
module HomepagesHelper
end

app/views/homepages/_form.html.haml
= form_for(link_form, url: links_path, remote: true) do |f|
  .form-row.align-items-center
    .col-sm-8.my-1
      %label.sr-only{ for: 'url' }= 'url'
      = f.text_field :url, class: 'form-control', type: 'text', id: 'url', placeholder: 'https://yoururltoshorten.com/example', autofocus: true
    .col-sm-4.my-1
      = f.submit 'Shorten', class: 'btn btn-primary btn-block', type: 'submit'

app/views/homepages/_link_row.html.haml
%tr{ id: link.id, class: 'link_row' }
  %td= link.url
  %td= link_to link.short, link.short, target: :_blank, rel: 'noopener'
  %td= link_to 'Graph', link_path(link.id)
  %td= link_to 'Delete', link, method: :delete, remote: true, class: 'js_delete_link'

app/views/homepages/_links_table.html.haml
.table-responsive-sm
  %table.table.table-hover.js_table_link_list
    %tbody
      - links.each do |link|
        = render 'link_row', link: link

app/views/homepages/index.html.haml
%div
  .jumbotron.text-center
    %h1.display-4= 'WizUrl'
    %p.lead.text-muted= 'An URL shortener'

  .container
    .row
      .col-sm-12
        = render 'form', link_form: @link_form
    .row.mt-5
      .col-sm-12
        .table-responsive
          = render 'links_table', links: @links
  
  = render 'shared/errors'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WizUrl</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
 
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
 
  <body>
    <%= yield %>
  </body>
</html>
 

app/views/links/_form.html.haml
= form_for(link, url: link_path, method: :get) do |f|
  .form-row.justify-content-end
    .col-sm-6.my-1
      %label.sr-only{ for: 'end_time' }= 'choose a time'
      %input.form-control{ type: 'datetime-local', value: @graph_link_presenter.end_time_to_string, max: @graph_link_presenter.max_end_time_to_string, id: 'end_time', name: 'end_time' }
    .col-4.my-1
      = f.submit 'Submit', class: 'btn btn-primary btn-block', type: 'submit'

app/views/links/show.html.haml
.container
  .card.mt-3.mb-4.box-shadow
    .card-header.text-center
      %h4.my-0.font-weight-normal= 'Graph click by minute for one hour'
    .card-body
      %ul.list-unstyled.mt-3.mb-4
        %li
          %span.font-weight-bold= 'Original URL:' 
          = link_to @graph_link_presenter.link.url, @graph_link_presenter.link.url, target: :_blank, rel: 'noopener'
        %li
          %span.font-weight-bold= 'Shortened URL:' 
          = link_to @graph_link_presenter.link.short, @graph_link_presenter.link.short, target: :_blank, rel: 'noopener'
      .row.align-items-center.mt-5
        .col-12
          = column_chart @graph_link_presenter.build_full_range, @graph_link_presenter.properties

      
      .row.justify-content-between.align-items-center.mt-5
        .col-sm-6
          = link_to 'Back to homepage', root_path
        .col-sm-6
          = render 'form', link: @link
  
    

app/views/shared/_errors.html.haml
%div{ id: 'message' }
  %div{ style: 'padding: 5px;' }
    .alert.alert-primary{ id: 'inner-message', role: 'alert' }

app/views/shared/_list_errors.html.haml
.row.align-items-center.js_list_errors
  .col-12-sm
    %ul.mb-0
      - errors.each do |error|
        %li= error